#ifndef _MINECRAFT_WORLD_LEVELCONSTANTS_H_
#define _MINECRAFT_WORLD_LEVELCONSTANTS_H_


const int LEVEL_HEIGHT = 128;
const int CHUNK_CACHE_WIDTH = 32; // in chunks (was 16)
const int CHUNK_WIDTH = 16; // in blocks
const int CHUNK_DEPTH = 16;
const int CHUNK_CACHE_MIN = -(CHUNK_CACHE_WIDTH / 2);
const int CHUNK_CACHE_MAX = CHUNK_CACHE_MIN + CHUNK_CACHE_WIDTH - 1;
const int LEVEL_WIDTH = CHUNK_CACHE_WIDTH * CHUNK_WIDTH;
const int LEVEL_DEPTH = CHUNK_CACHE_WIDTH * CHUNK_DEPTH;
const int LEVEL_MIN_X = CHUNK_CACHE_MIN * CHUNK_WIDTH;
const int LEVEL_MAX_X = LEVEL_MIN_X + LEVEL_WIDTH - 1;
const int LEVEL_MIN_Z = CHUNK_CACHE_MIN * CHUNK_DEPTH;
const int LEVEL_MAX_Z = LEVEL_MIN_Z + LEVEL_DEPTH - 1;
const int CHUNK_COLUMNS = CHUNK_WIDTH * CHUNK_DEPTH;
const int CHUNK_BLOCK_COUNT = CHUNK_COLUMNS * LEVEL_HEIGHT;

#endif
